### ISSUE TITLE
Send validation compares strings

### ISSUE THREAD

**Issue by haasted** [luniehq/lunie-light#271]
I had an issue in the e-money network where I was unable to send 3 NGM from an account with a balance of 100 NGM. Lunie told me that my balance was insufficient. 

The issue seems to be in `components/ActionModals/ActionModal.vue`, where a bit of investigation revealed that the comparison `balance.available >= amount` is actually comparing two strings in some cases. This will work as intended occasionally, e.g. if the balance had been 300 NGM or more, but does not work for this particular balance.

I created a local fix at https://github.com/e-money/lunie-light/commit/cfb0fa5b200a7966b1a2eade280358814d9cdb7f, but there might be other locations that need a similar treatment.

**Comment by Bitcoinera** [comment]
Hi Henrik. Thank you so much for opening this issue. Makes sense, this comparison should enforce the `Number` type. Thank you for bringing this to our attention.

What I am not sure about is if it is actually needed to compare using the `BigNumber` module. Since these amounts come already from the reducers, they shouldn't have more than six decimals, and this should be a non-brainer for the common `Number` type. I think, at least

**Comment by haasted** [comment]
Thanks for you quick reply.

The codebase is still new to me, so it's very possible that my approach is a bit over-engineered, and that the `Number` type is sufficient.
